---
- name: Diagnose Crashing Pod
  hosts: sno.manohar.in
  gather_facts: false

  tasks:
    - name: Get crashing pod information
      ansible.builtin.command:
        cmd: oc get pods -A -o wide
      register: pod_status
      changed_when: false

    - name: Display pod information
      ansible.builtin.debug:
        var: pod_status.stdout
