---
- name: Diagnose Crashing Pod
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Get crashing pods
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: aap
        kubeconfig: /root/.kube/config
      register: pods

    - name: Display crashing pods
      ansible.builtin.debug:
        msg: "{{ item.metadata.name }}"
      loop: "{{ pods.resources }}"
      when:
        - item.status.containerStatuses is defined
