---
- name: Get OpenShift Node CPU and Memory Usage
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Get node resource usage
      kubernetes.core.k8s_info:
        api_version: metrics.k8s.io/v1beta1
        kind: NodeMetrics
      register: node_metrics

    - name: Display node resource usage
      ansible.builtin.debug:
        msg: |
          Hostname     : {{ item.metadata.name }}
          CPU Usage    : {{ item.usage.cpu }}
          Memory Usage : {{ item.usage.memory }}
      loop: "{{ node_metrics.resources }}"
      loop_control:
        label: "{{ item.metadata.name }}"
