---
- name: OpenShift AAP Demo
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Check OpenShift authentication
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Namespace
      register: namespaces

    - name: Display authentication result
      ansible.builtin.debug:
        msg: "Successfully connected to OpenShift"

    - name: Display namespaces
      ansible.builtin.debug:
        msg: "{{ namespaces.resources | map(attribute='metadata.name') | list }}"
