---
- name: OpenShift Must-Gather
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Create Must-Gather directory
      ansible.builtin.file:
        path: "/tmp/openshift-must-gather"
        state: directory
        mode: "0755"

    - name: Run OpenShift Must-Gather
      ansible.builtin.command:
        cmd: oc adm must-gather --dest-dir=/tmp/openshift-must-gather
      register: must_gather
      changed_when: true

    - name: Display Must-Gather output
      ansible.builtin.debug:
        var: must_gather.stdout_lines

    - name: Display Must-Gather location
      ansible.builtin.debug:
        msg: "Must-Gather completed: /tmp/openshift-must-gather"
