---
- name: Diagnose Crashing Pod
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Get crashing pod
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: aap
        name: "{{ pod }}"
      register: crashing_pod

    - name: Display crashing pod
      ansible.builtin.debug:
        msg: "CRASHING PODS : {{ pod }}"
